name: CD Example Production
on:
  push:
    branches:
      - main


jobs:
    deploy:
        name: CD Example Production
        runs-on: ubuntu-latest
        steps:
        - name: Checkout My Code
          uses: actions/checkout@c4
        - name: SSH Connect
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secret.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              echo "Berhasil Konek ke Server"
              if [ -d "/SEMESTER 6/CICD" ]; then
                echo "Ada folder LSTW"
                cd /SEMESTER 6/CICD
                echo "Berhasil Masuk ke Folder LSTW" 
              else
                echo "Gak ada folder LSTW, membuat folder"
                mkdir /SEMESTER 6/CICD
                cd /SEMESTER 6/CICD